name: Chrome
on: push
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_host: localhost
          CYPRESS_port: 5173
